### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by baileyn** [Zlacki/OpenRSCD#1]
It seems you have a somewhat closed source licensing on a few of the files in this project. I was wondering if you're giving the users of this project permission via GPLv3, since it's in the LICENSE file in the root of the project. I wasn't sure if the following license was purposely left in place, or there's some extra baggage on those files.

```
    /*
     * packethandler.hpp
     *
     * Copyright (C) 2011-2012,  Alex Petrovich <alex@libslack.so>
     *
     * Unauthorized copying of this file, via any medium is strictly prohibited
     * Proprietary and confidential
     *
     */ 
```

**Comment by Zlacki** [comment]
GPLv3.  Appreciate your attention to detail and respect to licensing.  It's extra baggage; I will remove it at my earliest convenience.
